### PR TITLE
Switch NPM package to support only ESM

### PR DESCRIPTION
**Pull request by IvanGoncharov**
As disscussed during graphql-js-wg:
https://github.com/graphql/graphql-js-wg/blob/main/agendas/2022-03-30.md

### CODE REVIEW

**Comment by saihaj** [comment]
@IvanGoncharov what about #3361 ?

**Comment by IvanGoncharov** [comment]
> @IvanGoncharov what about #3361 ?

@saihaj As we agreed, let's try with full ESM first, and if the community strongly asks for CJS we can go the #3361 approach with dual packages.

**Comment by saihaj** [comment]
> > @IvanGoncharov what about #3361 ?
> 
> @saihaj As we agreed, let's try with full ESM first, and if the community strongly asks for CJS we can go the #3361 approach with dual packages.

I mean the work was already done there and we just need to that `esm` only package under main `graphql` npm

**Comment by IvanGoncharov** [comment]
> I mean the work was already done there and we just need to that esm only package under main graphql npm

@saihaj Can't do that, benchmark and integration tests need to use ESM, it's the absolute majority of changes in this PR.
https://github.com/graphql/graphql-js/pull/3361 don't do that.

**Comment by saihaj** [comment]
> > I mean the work was already done there and we just need to that esm only package under main graphql npm
> 
> @saihaj Can't do that, benchmark and integration tests need to use ESM, it's the absolute majority of changes in this PR. #3361 don't do that.

@IvanGoncharov we have tests in that PR 
image

**Comment by saihaj** [comment]
ok but we can just push a commit on initial work done there and wait for @graphql/graphql-js-reviewers team for review

**Pull request merged**
