### PR TITLE
polish: do not repeat isPromise check

### PR DESCRIPTION
**Pull request by yaacovCR**
If a field resolves asynchronously, then it will always complete asynchronously.

Adds additional test cases to complete code coverage.

### CODE REVIEW

**Comment by yaacovCR** [comment]
This has been extracted from #3754.

**Comment by yaacovCR** [comment]
On my machine this gives only a nominal speed improvement, so any other speed improvement would have to be from  #3754 

image

**Comment by yaacovCR** [comment]
> On my machine this gives only a nominal speed improvement, so any other speed improvement would have to be from #3754
> 
> image

I think I’m using the revs option incorrectly here, will update further if I get it right

**Comment by yaacovCR** [comment]
The purpose of this PR is just to make the diff for #3754 smaller and to test to make sure where the speed improvements for #3754 are coming from. See https://github.com/graphql/graphql-js/pull/3754#issuecomment-1339961683

**Review by saihaj — APPROVED** [review]

**Pull request merged**
