### PR TITLE
Add TS typings

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Copied from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/54712a7e28090c5b1253b746d1878003c954f3ff/types/graphql
All credits goes to original authors of '*.d.ts' files:
@TonyPythoneer @calebmer @intellix @firede @kepennar @freiksenet @IvanGoncharov @DxCx @rportugal @tgriesser @dyst5422 @adnsio @divyenduz @bradzacher @clayne11 @JCMais @langpavel @mc0 @martijnwalraven @jedmao

### CODE REVIEW

**Comment by TonyPythoneer** [comment]
But I have a question, had graphql team decided to maintain TS type?

Who can represent that and explain the Management Strategy of open source?

**Comment by IvanGoncharov** [comment]
@TonyPythoneer What do you mean by `graphql` team?
Here is the list of contributors: https://github.com/graphql/graphql-js/graphs/contributors
I'm volunteering to support this TS typings with help of community so I don't see any problems here.

**Comment by TonyPythoneer** [comment]
@IvanGoncharov 
Sorry, I just acted emoji to express my emotion before typing 
It's because English is not my native language, I need time to type.

If you're available, please read my reply. thx.
https://github.com/graphql/graphql-js/pull/2102#issuecomment-523535958

**Comment by bradzacher** [comment]
From my POV - I could care less.

It's not like the history has been completely omitted - the merge commit was created with the same description as this PR: https://github.com/graphql/graphql-js/commit/d1391eea86caf030f1945a518aeadb6e2d3e7c20
Which means that looking at the file's history, you will be able to follow the link to the original file within the DefinitelyTyped repo. Additionally all the contributors are directly tagged in the commit.

**Comment by IvanGoncharov** [comment]
@TonyPythoneer Sorry, I didn't refresh this issue before merging so I didn't saw you updated your comment. Also not sure if people are notified since GitHub sent email only then you post a comment not than you update it.

@TonyPythoneer Even though code in question is under MIT license (same as this library) if you or any other author oppose your code being merged I can revert this commit and rewrite it from scratch.
I believe the end result would be pretty similar since typings are based on Flow types and JSDoc comments.

**Comment by intellix** [comment]
Awesome stuff! Just yesterday I noticed DefinitelyTyped was missing the new utility trimIgnoredCharacters :)

**Comment by TonyPythoneer** [comment]
@IvanGoncharov You can send new PR to add the authors info. It’s okay.

**Comment by TonyPythoneer** [comment]
BTW @IvanGoncharov 
Please note ti will have more tasks need to do.

1. Tell admin of DefinitelyTyped team that the typing can get removed because it has migrated.
2. Tell other contributors on DefinitelyTyped who are actively in that. They should stop sending PR to DefinitelyTyped. In the future, it should focus on here.

This is my opinions.

**Comment by IvanGoncharov** [comment]
>  You can send new PR to add the authors info. It’s okay.

@TonyPythoneerWe don't have such list in any other file so I moved it to README please see #2103

**Comment by IvanGoncharov** [comment]
> BTW @IvanGoncharov
Please note ti will have more tasks need to do.

> Tell admin of DefinitelyTyped team that the typing can get removed because it has migrated.
Tell other contributors on DefinitelyTyped who are actively in that. They should stop sending PR to DefinitelyTyped. In the future, it should focus on here.
This is my opinions.

@TonyPythoneer Yes definitely. After I release `14.5.0` I plan to follow the standard algorithm for removing the package from DefinetlyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by TonyPythoneer** [comment]
Okay, It looks good to me. thx

**Comment by langpavel** [comment]
I'm happy that TS definitions are now part of this library,
but I'm not so happy with the way it's done. Feels a little like stealing. I can see @TonyPythoneer point of view — I'm participant to both, graphql-js and DT types.

What I miss is more transparent strategy for future contributions. How TS typings will be enforced?

By merging, but not adopting — you @IvanGoncharov  — take responsibility for type definitions.
- Do you have strategy for adopting typescript?
- Shall we expect transition of `graphql-js` to TS?
- What about `flow`? (I'm not worry, but someone can?)

**Comment by IvanGoncharov** [comment]
> I'm happy that TS definitions are now part of this library,
but I'm not so happy with the way it's done. Feels a little like stealing.

@langpavel I'm confused about "stealing" part. Both commit and PR have clear attribution and link to the original source also on @TonyPythoneer request I added credits to README see #2103 

Since legally this repository belongs to GraphQL Foundation (I'm not a member, just a person who got commit rights in this repo) I don't want to make foundation responsible for my decisions.
Even though `*.d.ts` files were distributed under MIT, if you or any other the authors don't want them to be included in this repo I can revert entire PR or alternative only specific parts that you contributed:
image

@langpavel Can you please respond on how this situation can be resolved?

> By merging, but not adopting — you @IvanGoncharov — take responsibility for type definitions.

I always take responsibility for everything that I merge or commit to this and other repos that I maintain. Even if PR comes from other developers I still take personal responsibility for stuff that I merge.

That said I can't guarantee the enterprise level of support since I'm maintaining this library in my own free time. But I always try to respond on issues and PRs within a day and if I disagree with the proposed fix I always try to come up with an alternative in the reasonable amount of time.

> Do you have strategy for adopting typescript?

At the time of this PR, I was still in the process of discussing it with GraphQL Foundation.
After I got the green light from GraphQL Foundation I started a public discussion in #2104 (**Please keep this discussion technical and connected to the actual plan**)

> What about flow? (I'm not worry, but someone can?)

We will continue to provide Flow typings as part of this repository, please see #2104

**Comment by langpavel** [comment]
I'm really sorry about *stealing* word. It may sounds much harder than I wish…

**Comment by victortwc** [comment]
Requires typescript 3+ and breaks projects with old typescript support.

**Comment by victortwc** [comment]
Isn't is better to be optional and move this to @types/graphql ?

**Comment by mortenbroesby** [comment]
+1 on making the types be optional, using @types/graphql

**Comment by IvanGoncharov** [comment]
> I'm really sorry about stealing word. It may sounds much harder than I wish…

@langpavel Thanks for clarification 👍 I have no hard feelings. Glad it resolved.
Sorry for being too formal but I'm really worried about the legal side of things since I'm not an owner of this project.

At the same time, I think we need to be more transparent with the roadmap and discuss it more with the community.

> Requires typescript 3+ and breaks projects with old typescript support.

@victortwc At some point even `DefinetlyTyped` will be forced to switch to typescript 3+
In the case of `graphql-js` we will continue to maintain `14.5.x` line until v16 releases (after Jan 2020, to drop Node8). 

Having separate `@types/graphql` will create a lot of confusion and will also split maintaining efforts from the community. But more importantly, we need to switch TS to prevent community split since I see more and more attempts to rewrite `graphql-js` in TypeScript, e.g. [here](https://github.com/ponkey364/graphql-deno) and [here](https://github.com/apollographql/graphql-js#graphqljs).
We either rewrite `graphql-js` in TS or we risking to have community split between `graphql-js` and it's TS fork.

**Pull request merged**
