### PR TITLE
Error: make 'path' and 'locations' enumerable only if present

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Also cleanup tests from 'undefined' and 'containSubset'.

@leebyron I split up non-breaking changes from #1284 
I think they are useful by itself since they make tests more readable.

### CODE REVIEW

**Comment by leebyron** [comment]
This looks great - do you mind rebasing and looking at the tests? Looks like the build is failing with test failures

**Comment by IvanGoncharov** [comment]
@leebyron Fixed. To make validation tests less fragile I made them expect a subset of errors.

**Comment by leebyron** [comment]
That seems okay, but I'm not sure that I would agree that makes them less fragile - it just means they're more likely to pass when really there is an error.

Ideally these should detect the exact set of schema validation errors and we should write the test so that each test introduces only the validation error it expects to catch

**Comment by leebyron** [comment]
Going to merge this, but we should still try to improve those tests

**Pull request merged**
