### PR TITLE
Reactive GraphQL

### PR DESCRIPTION
**Pull request by xareelee**
This PR is only for discussion about Reactive GraphQL we discussed before in the https://github.com/graphql/graphql-js/issues/647#issuecomment-290572791.

Here are what I did in January (sorry for delayed PR):

* Rewrite the `graphql.js` using **RxJS** to replace Promise-based `graphql.js` (all tests passed, you could run ). Run `yarn run testonly-rx`.
* Rewrite the `graphql.js` using **most.js** to replace Promise-based `graphql.js` (one test failed, still unresolved). Run `yarn run testonly-most`.
* Write `benchmark.js` to test the performance for Promise-based, RxJS-based and Most.js-based `graphql()`. Run `yarn run benchmark`.

Current progress:

* Finish a refactored `graphql` version for reactive programming.
* Pass tests (RxJS-based version)

Current Issues:

* The Most.js-based `graphql()` failed one test (has been reported at https://github.com/cujojs/most/issues/404).
* The RxJS-based and Most.js-based `graphql()` with reach a memory issue when running benchmark — **"JavaScript heap out of memory"**

TODO (if we agree to keep going this fork):

* [ ] Figure out the memory issues using RxJS and most.js with GraphQL.
* [ ] Make sure it is useful for real world and add more tests for reactive programming.
* [ ] Further refactoring to remove using `exeContext.errors.push` and use reactive `Observable.error()` instead of `throw` for error-handling.
* [ ] Rewrite the `graphql.js` with callback functions or our own version of Monad for Reactive Programming without any 3rd-party Rx dependency.
* [ ] Fix code for flowtype and lint.
* [ ] Make performance better (at least not significantly worst than Promise-based graphql).

### CODE REVIEW

**Comment by Birowsky** [comment]
@xareelee  i would love to know whether there is any progress here or whether you figured out what caused the memory issue with rx.

**Comment by xareelee** [comment]
@Birowsky sorry, I'm working in ofo (China's biggest bike-sharing startup) and I'm too busy in this year.

**Comment by dotansimha** [comment]
@DxCx

**Comment by Birowsky** [comment]
@xareelee no problemo, have fun mate!

**Comment by stubailo** [comment]
BTW there's also this implementation: https://www.npmjs.com/package/graphql-rxjs

**Comment by leebyron** [comment]
For repo maintenance I'm going to close this issue. I'm happy to see the experimentation of a reactive executor in related github projects!

**Comment by alexstrat** [comment]
For anyone around here, I stumbled upon this very promising implementation and amazing work: https://github.com/mesosphere/reactive-graphql

👏

**Pull request closed without merging**
