### PR TITLE
Add missing export for "findBreakingChanges" function

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Nothing to add to the title :)

@wincent Can you please merge it?

### CODE REVIEW

**Comment by wincent** [comment]
Thanks @IvanGoncharov.

**Comment by IvanGoncharov** [comment]
@wincent Can you please publish NPM package?

**Comment by wincent** [comment]
@IvanGoncharov: will wait a day or two to see if anything else should land first, but should be able to cut a release this week.

**Comment by wincent** [comment]
And I did not get to the release last week, but still aiming to get it done soon.

**Pull request merged**
