### PR TITLE
Bugfix getArgumentValues: DefaultValue not used

### PR DESCRIPTION
**Pull request by andimarek**
When no argument was provided, the defaultValue should be used as argument value

### CODE REVIEW

**Comment by leebyron** [comment]
Thanks! Could you add a test illustrating this?

**Comment by andimarek** [comment]
I added a test but it's much more unit-test than the usual test cases. For example I create an argument object (representing a argument literal) directly instead letting the parser do that.

So I don't know if this fits in the general project philosophy.

**Comment by leebyron** [comment]
The unit test is nice, but it's also helpful to have more of an integration test with the executor to ensure that the use case in question is covered.

**Comment by leebyron** [comment]
there are examples of this in executor/__tests__/variables.js

**Comment by andimarek** [comment]
I added a more like integration test. The first unit-test could be removed, but also kept ... both are fine options. (imho)

**Comment by andimarek** [comment]
ok ... now the tests also pass :-)

**Comment by leebyron** [comment]
Just merged this in 08559470ab5b7bd4621128add4b1f7a5afde876c after squashing the commits and making some minor amendments.

Thanks again for investigating and fixing this!

**Pull request closed without merging**
