### PR TITLE
polish(ast): prefer undefined over empty arrays

### LINKED ISSUE #2203: Test all functions (with AST input) that they handle `undefined` instead of array properites
Based on @mjmahone comment https://github.com/graphql/graphql-js/pull/2084#discussion_r313964490
> I know we ran into problems in the past when hand-modeling the AST where, unless you explicitly set directives: [], you'd end up getting an undefined reference, even though the flow type allowed it.

Currently `parse` always return empty arrays (and never `undefined`) but AST definitions explicitly support `undefined`. 

This is done to make AST forward-compatible meaning old code that generate/transformate AST and doesn't know about new properties (e.g. `interfaces` on `InterfaceTypeDefinitionNode` node) is still compatible with newer versions of `graphql-js`.

It also means it's very easy to manually create nodes, for example creating `FieldNode` you can safely omit `arguments`, `directives` and `selectionSet` properties so minimal field will look like:
```js
{
  kind: 'Field', 
  name: { kind: 'Name', value: 'foo' },
}
```

At the same time we need to be sure that functions like `buildSchema`, `extendSchema`, `print`, `execute`, etc. are actually ready to handle such functions and don't crash when they get `undefined` instead of an empty array.

### PR DESCRIPTION
**Pull request by yaacovCR**
see: https://github.com/graphql/graphql-js/pull/2405#issuecomment-579077133

Manually created ASTs always allowed undefined in place of empty arrays; this change simply updates the parser to more closely follow the manual approach. This is therefore not technically a breaking change, but considering that there may be tools not aware of this, we have labelled it a BREAKING_CHANGE to highlight it for consumers.

This closes #2203 as our tests now cover the undefined case by default whenever there is an empty array.

### CODE REVIEW

**Comment by yaacovCR** [comment]
Wo! This is much more involved to do consistently => and I am not sure worth the effort. Closing for now, anybody interested can take this as a starting point if they want.

**Comment by yaacovCR** [comment]
Well, it works!

It would seem that it's more accurate to use undefined when an `optionalMany(...)` is skipped entirely and an empty array when it is found, but has an empty list. So, it would seem that this PR is technically more correct.

Peeking around at https://astexplorer.net/ it seems that TS parser has some empty arrays, some undefined, while for Babel I didn't on a very cursory look see any undefined.

But still not 100% sure this is too compelling, with the status quo being somewhat compelling! Comments welcome!

**Review by Thompson1985 — APPROVED** [review]

**Comment by yaacovCR** [comment]
Merging this PR allows us to close #2203, improving robustness of our test coverage. Presumably our downstream users were also affected by #2203 and had to account for manually created AST nodes, so they should be robust to this change, but I upgraded it to a breaking change anyway just to call it out.

**Review by JoviDeCroock — APPROVED** [review]

**Comment by JoviDeCroock** [comment]
Probably needs a rebase

**Review by JoviDeCroock — APPROVED** [review]

**Pull request merged**
