### PR TITLE
fix(stream): allow initialValue of zero

### PR DESCRIPTION
**Pull request by yaacovCR**

### CODE REVIEW

**Comment by yaacovCR** [comment]
@IvanGoncharov 

I am not sure why the flow integration tests fail -- they pass if we bump the flow version used in integration tests to 0.142 to match the base repo.

On the other hand, if I downgrade the base repo to 0.135, it triggers the following seemingly unrelated errors:

```
> graphql@15.4.0 check C:\Users\Adina\Documents\GitHub\graphql-js
> flow check

Error ---------------------------------------------------------------------------------------- flow-typed/core.js:131:28

Please add `...` to the end of the list of properties to express an inexact object type. [implicit-inexact-object]

   131|     static entries<T>(obj: { [key: string]: T, __proto__: null }): Array<[string, T]>; // graphql-js HACK
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error ---------------------------------------------------------------------------------------- flow-typed/core.js:131:28

Please write this object type as explicitly exact (use `{|` and `|}` instead of `{` and `}`) or as explicitly inexact
(add `...` to the end of the list of properties). [ambiguous-object-type]

   131|     static entries<T>(obj: { [key: string]: T, __proto__: null }): Array<[string, T]>; // graphql-js HACK
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error ---------------------------------------------------------------------------------------- flow-typed/core.js:223:27

Please add `...` to the end of the list of properties to express an inexact object type. [implicit-inexact-object]

   223|     static values<T>(obj: { [key: string]: T, __proto__: null }): Array<T>; // graphql-js HACK
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by yaacovCR** [comment]
huh. and now integration tests are passing again. wierd.

**Comment by yaacovCR** [comment]
I didn't bother adding an additional test -- the existing code was not allowing an asynciterator to stream initialValues=0, was always acting as if initialValues was at least 1.

**Comment by yaacovCR** [comment]
@robrichard @IvanGoncharov ready for review

**Comment by robrichard** [comment]
@yaacovCR can you add a test for this case?

**Comment by yaacovCR** [comment]
Sure

**Comment by yaacovCR** [comment]
Done

**Pull request merged**
