### PR TITLE
build/npm: add TS transformation that optimise for-of on arrays

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Context: I wanted to try more automatic alternative to #3687 that
allows us to continue using ES6 features without perfomance lost.

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
@IvanGoncharov https://astexplorer.net/#/gist/54f452efefc94d565223d4296a91172e/84b9951249ac82a140e5aeafa3bec78c9861dd96 this would do the array destruct optimizations

**Comment by yaacovCR** [comment]
@JoviDeCroock  do you know the status of this one by any chance?

**Comment by JoviDeCroock** [comment]
@yaacovCR I don't no

**Comment by yaacovCR** [comment]
Closing in favor of #4208

**Pull request closed without merging**
