### PR TITLE
subscribe: once execution starts....

### PR DESCRIPTION
**Pull request by yaacovCR**
data should return null?

### CODE REVIEW

**Comment by yaacovCR** [comment]
See some discussion in https://github.com/graphql/graphql-spec/pull/894

See additional rough thoughts on how subscriptions fit in at: https://github.com/graphql/graphql-js/pull/3621#issuecomment-1150280432

**Comment by benjie** [comment]
The transition between "request error" (payloads like `{errors: GraphQLError[]}`) and "field error" (payloads like `{data: object | null, errors?: GraphQLError[]}`) in the spec doesn't seem to happen at explicitly designated boundaries, but here's my take:

If a "request error" is raised, then that's seen as being "before execution" (even if it's part of ExecuteRequest(), for example the "request error" raised by [CoerceVariableValues()](https://spec.graphql.org/draft/#CoerceVariableValues()).

Asserts don't define an error type because they should not happen (due to validation, etc); but I see the assert in ExecuteQuery() and ExecuteMutation() as raising a "request error" (since there is no field at that point). Once these algorithms have moved onto the `ExecuteSelectionSet` phase we're out of "request error" phase and into "field error" phase.

For subscriptions the definition is somewhat harder to discern. Do we introduce the "boundary" before or after step 10 of [CreateSourceEventStream()](https://spec.graphql.org/draft/#CreateSourceEventStream())? What happens if the call to `ResolveFieldEventStream` results in an error?

One option is that _because_ this is an error in a field method, it _is_ a field error, and thus the division between "request error phase" and "field error phase" is between steps 9 and 10 of CreateSourceEventStream:

> 9. Let argumentValues be the result of [CoerceArgumentValues](https://spec.graphql.org/draft/#CoerceArgumentValues())(subscriptionType, field, variableValues)
> ***\~\~BOUNDARY\~\~***
> 10. Let fieldStream be the result of running [ResolveFieldEventStream](https://spec.graphql.org/draft/#ResolveFieldEventStream())(subscriptionType, initialValue, fieldName, argumentValues).

So an error raised whilst creating the stream _for a field_ should be treated as a field error, and thus should result in the field itself being null. However, this may be surprising to the user who is expecting a stream not a singular payload.

It seems to me that if you fail to create the event stream then that should be a request error (you've failed to set up a subscription, so the operation has failed). I.e. rather than putting the boundary at the aforementioned position, I think it should probably be once you enter [MapSourceToResponseEvent()](https://spec.graphql.org/draft/#MapSourceToResponseEvent()). But honestly, I could go either way on this. There does seem to be ambiguity here, but I'd have to read the spec more fully again to figure out if this was defined or not.

**Comment by yaacovCR** [comment]
> It seems to me that if you fail to create the event stream then that should be a request error (you've failed to set up a subscription, so the operation has failed). I.e. rather than putting the boundary at the aforementioned position, I think it should probably be once you enter [MapSourceToResponseEvent()](https://spec.graphql.org/draft/#MapSourceToResponseEvent()). But honestly, I could go either way on this.

I guess any type of error for CreateSourceEventStream leads to failed input for MapSourceToResponseEvent which is a kind of request error…

I think this needs more hardening in the spec and likely a better way to distinguish between error types than the existence of data:null which doesn’t make much sense for subscriptions.

i am going to close this for now, but it’s here if we want to revisit

**Comment by benjie** [comment]
In summary, my current opinion is that "execution begins"

- for queries: when you enter [ExecuteQuery()](https://spec.graphql.org/draft/#ExecuteQuery())
- for mutations: when you enter [ExecuteMutation()](https://spec.graphql.org/draft/#ExecuteMutation())
- for subscriptions: when you enter [MapSourceToResponseEvent()](https://spec.graphql.org/draft/#MapSourceToResponseEvent())

**Comment by yaacovCR** [comment]
That makes data:null match current behavior, but I think a spec improvement would make all this explicit and also explicitly acknowledge that with subscriptions, there are two rounds of execution, one that sets up the source stream and one for each event....

**Comment by benjie** [comment]
Yeah, I agree that clarity here should come from the spec.

**Pull request closed without merging**
