### PR TITLE
Rewrite createSourceEventStream to avoid use of `async`

### PR DESCRIPTION
**Pull request by wincent**
We should avoid a runtime dependency on `async` support because we want the graphql package to work in as many contexts as possible with minimal configuration.

As of 0779c36f9ba621d2d4a045, even a simple invocation usage of the package like the one in the tutorial (http://graphql.org/graphql-js/) will cause an error in the absence of the regenerator runtime:

    ReferenceError: regeneratorRuntime is not defined

Rather than depending on the runtime, let's just rewrite the function to not use `async`. In order to do this, we have to drop the use of the `await` keyword inside the function and make it explicitly return a promise.

Flow and tests pass.

There is a fair bit of whitespace-only change in this, so you may want to view the diff without it (with `git diff -b` or even `git diff -w` for example).

Closes: https://github.com/graphql/graphql-js/issues/1006

### CODE REVIEW

**Comment by wincent** [comment]
Also tested this with the simple `server.js`:

```
var { graphql, buildSchema } = require('graphql');

// Construct a schema, using GraphQL schema language
var schema = buildSchema(`
  type Query {
    hello: String
  }
`);

// The root provides a resolver function for each API endpoint
var root = {
  hello: () => {
    return 'Hello world!';
  },
};

// Run the GraphQL query '{ hello }' and print out the response
graphql(schema, '{ hello }', root).then((response) => {
  console.log(response);
});
```

And a `npm link`-style symlink in a project with nothing else in it:

```
{
  "name": "repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "graphql": "0.11.0"
  }
}
```

Before:

```
ReferenceError: regeneratorRuntime is not defined
```

After:

```
{ data: { hello: 'Hello world!' } }
```

**Comment by wincent** [comment]
Would also like to set up a lint rule to disallow the use of `async`/`await` outside the test suite, but I don't think there is an eslint rule for that. :cry:

**Comment by wincent** [comment]
Merging this to get a mitigation out quickly. Can follow-up later if there is any other feedback.

**Comment by robzhu** [comment]
Thanks for the fix, this was totally my fault =(.

**Comment by wincent** [comment]
> Thanks for the fix, this was totally my fault

A very easy "mistake" to make. I blame not having a linter, but now we have one. :smile:

**Pull request merged**
