### PR TITLE
allows passing --watch to npm run testonly

### PR DESCRIPTION
**Pull request by yaacovCR**
https://github.com/TypeStrong/ts-node/issues/266

### CODE REVIEW

**Comment by yaacovCR** [comment]
Running prettier on my machine causes a large diff @IvanGoncharov  any ideas?

**Comment by yaacovCR** [comment]
zapped node_modules, presto, @IvanGoncharov, ready for review

**Comment by yaacovCR** [comment]
@IvanGoncharov can we merge this, very helpful for me :)

**Comment by IvanGoncharov** [comment]
@yaacovCR Sorry for the wait, trying to catch up with my GitHub inbox 😞 
If you have any other PR/issues blocking you please ping me in Slack.

**Pull request merged**
