### PR TITLE
OverlappingFieldsCanBeMergedRule: Fix performance degradation

### PR DESCRIPTION
**Pull request by AaronMoat**
Applies fixes from https://github.com/graphql/graphql-js/pull/3958 into 16.x.x, fewer changes as no stream support in 16.

### CODE REVIEW

**Comment by AaronMoat** [comment]
@IvanGoncharov how closely do I need to pay attention to the codecov failure on this backport branch?

**Comment by IvanGoncharov** [comment]
> @IvanGoncharov how closely do I need to pay attention to the codecov failure on this backport branch?

@AaronMoat Sadly it breaks CI, but you can add a C8 comment to ignore those lines.

**Comment by AaronMoat** [comment]
Thanks @IvanGoncharov - added!

**Comment by AaronMoat** [comment]
Thanks @IvanGoncharov, appreciate all your help on this one! Is there a request a release for 16? As best I can tell this is manual not automated

**Pull request merged**
