### PR TITLE
Workaround for codesandbox having bug with TS enums

### LINKED ISSUE #3685: Codesandbox - TypeError: Cannot read properties of undefined (reading 'FIELD')
Looks like at Version 16, the `graphql` module stopped functioning in CodeSandbox. 
Any import statement will throw the TypeError `Cannot read properties of undefined (reading 'FIELD')`
Has anyone had any experience with this?

Example of this issue:
https://codesandbox.io/s/graphql-field-error-eih7xb?file=/src/index.js

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Fixes #3685
Since we decide to get rid of TS enums in v17 anyway just add this
workaround to v16

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@github-actions publish-pr-on-npm

**Comment by hwillson** [comment]
👋 @IvanGoncharov - is there anything remaining here to get this merged in? Thanks!

**Comment by IvanGoncharov** [comment]
@hwillson I wanted to also prepare a solution on main, but since we decided to get rid of TS enums anyway, we can fix it just in v16 for now.
Thanks for the ping I will release it shortly.

**Comment by IvanGoncharov** [comment]
@hwillson Published in https://github.com/graphql/graphql-js/releases/tag/v16.6.0

**Pull request merged**
