### PR TITLE
Intial refactoring to work over observables instead of promises

### PR DESCRIPTION
**Pull request by DxCx**
First Implementation for #501 .
NOTE: Promises still works, this change does not break any existing usage.

TODO:
- [ ] Get CR Notes.
- [ ] Update any documentation? Which?
- [ ] Replace Observables Library? set it to peer instead of dependency? pending a decision on issues.
- [x] Reactive Execution:
  - [x] remove TODO and enable reactive execution.
  - [x] write tests with reactive execution.
  - [x] make sure to `take(1)`  when non-reactive request executes and observable is resolved.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by DxCx** [comment]
Hi @leebyron can you please review this?
I'm very eager to hear your thoughts about this.

**Comment by leebyron** [comment]
While I'm excited to support fields that return Observable values, I don't support this approach.

First, we shouldn't take a dependency on a large library like rxjs, either directly or as a peer dependency. Second, we should minimize the set of changes to the core executor. Third, we still need to support Promises/Thenable as the most common use case.

**Comment by leebyron** [comment]
I'm in favor of continued experimentation in this area though. This is closely aligned with some other earlier experiments to add @live to GraphQL.

**Comment by DxCx** [comment]
Hi @leebyron thanks for the quick response :)
I agree about the rxjs dependency, that's why i've opened it under discuession, and pending to hear what do you think should be supported..
also, if you will note, i did the minimal change to run over observables rather then promises.
then, in the end of the pipe, execute converts the observable into a promise, so no interface is broken.
and promises are still supported.

**Comment by leebyron** [comment]
Another question is what we actually want to see from a reactive GraphQL executor. We probably do not want to re-execute fields that are likely to have not changed and the output should be a series of diffs to send over the network rather than a series of whole values

**Comment by DxCx** [comment]
hehe, seems that we are aligned, just released today [rxjs-diff-operator](https://www.npmjs.com/package/rxjs-diff-operator) which is exactly for that purpose.

the update logic is same as the old one, so basiclly, static values will not be re-executed,
promises are Observables.fromPromise(1) which is observable of 1 value, so they won't reexecute either.
the only re-execution that accurs from my testing was when the subscription is Observable,
then for each value emitted, the ObjectType resolvers will be updated with a new root value from the subscription, however, this is the expected behavior as i see it.

**Comment by DxCx** [comment]
hi @leebyron, eventually i decided to create a seperated npm [(graphql-rxjs)](https://www.npmjs.com/package/graphql-rxjs) package for this for the moment being.
this way i can experiment it myself,
i'm planing on creating example app that uses it so you can experiment yourself.

**Comment by stubailo** [comment]
Really excited to see where this goes. I think observables in the resolver return can be a neat way to do subscriptions as well.

**Comment by DxCx** [comment]
hi @leebyron,

i have a server side example (getting graphiql with subscription over observables)
i thought i posted it a while ago and now i see that i didn't :(

so, if you want to take a look,
https://github.com/DxCx/webpack-apollo-server/tree/rxjs-subscriptions
specifically, on main.ts i define a channel (https://github.com/DxCx/webpack-apollo-server/blob/rxjs-subscriptions/src/main.ts#L15)
and then i use it inside a resolver (https://github.com/DxCx/webpack-apollo-server/blob/rxjs-subscriptions/src/schema/modules/subscription.ts#L10)

if you want to really play with it, just npm install & npm start.
then you will have a graphiql interface with the subscription on port 3000.

Other then that, i'm not sure what are you against in here,
are you against for the general concept of using Observables along with promises? (which feels much more intuitive versus the pub/sub solution found today)
or for the dependency of rxjs?

also, once this is resolved i would be happy to work on the @defer/@live/@stream directives as well as with observables it's very easy to implement.

**Comment by DxCx** [comment]
@leebyron can you please reply?

**Comment by leebyron** [comment]
Hey @DxCx, sorry for the delayed response.

Since this library primarily serves to be a production node server and reference implementation of the spec, I don't think it's the appropriate place for this kind of experimentation for fear that other implementations would see it as part of the direction of GraphQL, and this is not yet what we'd like to do. 

Notably - it's important that the execution code align to the spec to be a good reference implementation.

I do think it's a great idea to experiment with observable-based resolvers, it's an exciting idea that deserves to be explored - but I think that exploration deserves it's own repository which can move quickly and experiment with different ideas without worrying about breaking core users.

**Comment by leebyron** [comment]
I'm going to close this PR since we don't want to pursue this in this repository - I'm looking forward to seeing your work as a separate package.

**Comment by DxCx** [comment]
hey @leebyron 
after seen the work on subscription i was thinking,
if i'll rewrite this using AsyncIterator instead of Observables, is that something you will accept?

i mean, i want to introduce some execute function (`executeReactive`?) which is able to return more then one result potentially.

**Comment by smkhalsa** [comment]
Hey @leebyron,

Now that AsyncIterator has [reached Stage 4](https://github.com/tc39/proposals/commit/a41dccc91675f41c65dee354c18c19946d6f2f45), I'd love to hear your thoughts on @DxCx 's proposal above to add AsyncIterator support to the execute function. The ability to return multiple results from the execute function would be a huge step forward for live queries. Thanks!

**Comment by leebyron** [comment]
A live query would need a separate core executor. It might use some parts
of the algorithm which are the same, however the live executor will have
different concerns, so we should not convert the existing executor to be a
live executor.

I agree that for a live executor, AsyncIterators will be an important
implementation detail, however I’d recommend accepting either AIs or
Observables from resolver functions

**Comment by smkhalsa** [comment]
@leebyron That makes sense. I believe that @DxCx 's [graphql-rxjs](https://github.com/DxCx/graphql-rxjs) takes this approach, with a separate `executeReactive` executor. 

Would you consider a PR for adding reactive executors to the library at this time? Thanks again!

**Comment by leebyron** [comment]
At this point I think it makes sense for add on libraries to work out
different approaches. If one approach becomes robust to all use cases we
could consider merging it into this library

**Pull request closed without merging**
