### PR TITLE
Integration tests for bundlers

### PR DESCRIPTION
**Pull request by danielrearden**

### CODE REVIEW

**Comment by kadirselcuk** [comment]
Merhaba TurkDevOps Kuruluşu hakkındaki düşünceleriniz nelerdir?
Bu alanlar için yardımcı olmanız beni çok onurlandırır
Herkese teşekkürler

**Comment by saihaj** [comment]
Hey @danielrearden what is missing here to convert this Draft to ready?

**Comment by renatobenks** [comment]
Interesting this level os tests 🤔

**Comment by IvanGoncharov** [comment]
@saihaj I added a very basic webpack test in #3188
I think we should work just expend it every time someone reports an issue with webpack or any other bundler.
Don't see anything else we need to test ATM so closing this PR.

**Pull request closed without merging**
