### PR TITLE
make schema creation lazier

### PR DESCRIPTION
**Pull request by yaacovCR**
if getPossibleTypes and/or getImplementations are never called on a schema, the schema does not have calculate the implementation map at startup

### CODE REVIEW

**Comment by yaacovCR** [comment]
[graphql-executor](https://github.com/yaacovCR/graphql-executor) never calls these subfunctions, as there are equivalent (cross realm compatible) versions

**Comment by IvanGoncharov** [comment]
@yaacovCR What's your motivation for this change?
Lazy evaluations make code more complicated and in general, we try to keep stuff immutable.
Performance-wise I don't see any difference even with the huge GitHub's schema we use in benchmark:https://github.com/graphql/graphql-js/runs/4736844456?check_suite_focus=true

**Comment by yaacovCR** [comment]
The motivation is as above. I want eventually a way to quickly serialize schemas and their metadata. I basically have one within executor schema construct in graphql executor, but it would help if schema metadata was only generated if needed.

**Comment by yaacovCR** [comment]
In terms of code complexity, I believe the PR demonstrates that this is not a complex change. Is there a particular part that bothers you?

**Comment by yaacovCR** [comment]
Hmmmm will have to look closer as to whether benchmark GitHub schema uses a lot of interfaces, maybe not a big deal

**Comment by yaacovCR** [comment]
Closing for now, just a reminder to me to benchmark before proposing any optimization

**Pull request closed without merging**
