### PR TITLE
Bring back `getDescription` export

### PR DESCRIPTION
**Pull request by stubailo**
We were using this in graphql-tools with graphql@0.11, would be nice to get it exported again!

### CODE REVIEW

**Comment by stubailo** [comment]
OK looks like there are some typing things to work through, I will come back to it tomorrow.

**Comment by leebyron** [comment]
You should also have this exported from index.js if you expect to use it in a dependent library, otherwise it might be too easy to regress again! We assume exports used between files are used purely internally.

It might be helpful to audit for other deep require uses as well to avoid future breakage

**Comment by stubailo** [comment]
@leebyron happy to make that modification for sure, we definitely have 3-4 others we are using. Didn't realize that was the intention with the internal exports!

Any idea what the argument type should be here? I would have thought `ASTNode` would have been the right thing, but I guess not all nodes have descriptions. Maybe I should just write some custom duck type thing.

**Comment by leebyron** [comment]
Try out `{ +description?: StringValueNode }`?

**Comment by stubailo** [comment]
OK looks like it's all good now, thanks for the suggestions!

**Comment by leebyron** [comment]
Nice. I'll likely have a point release out today or tomorrow that will include this.

Also, apparently this is your first commit to GraphQL.js. Congrats! 🎉

**Comment by stubailo** [comment]
> Also, apparently this is your first commit to GraphQL.js. Congrats! 

That is SO SURPRISING. I'll look into contributing more! I guess I spent more time on GraphQL.org that I misattributed.

**Comment by nodkz** [comment]
I'm also using `getDescription` method in graphql-compose.
Glad that it already fixed. Thanks, Sashko! 👍

Lee, all other "breaking" changes did not hit my tests and all works like a charm. 👌
With Flow just change array on $ReadOnlyArray in several places. Typings became much stronger. Thanks for this!!! 💪

**Comment by negezor** [comment]
@leebyron hi, when can you update package?

**Pull request merged**
