### PR TITLE
type/introspection: add missing `__Directive.args(includeDeprecated:)`

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Backport #3273

### CODE REVIEW

**Comment by falkenhawk** [comment]
Thank you @IvanGoncharov ! Any ETA of v15.6.1? 😅

**Comment by chenrui333** [comment]
Not sure if it is related, but I have run into some upgrade issue (from 15.5.1 to 15.8.0)

> Required input field xxx cannot be deprecated.

**Comment by saihaj** [comment]
@chenrui333 can you file an issue with an example?

**Comment by chenrui333** [comment]
Yeah, sounds good.

**Pull request merged**
