### PR TITLE
buildClientSchema: include standard type only if it is used

### PR DESCRIPTION
**Pull request by IvanGoncharov**
To be merged in `15.0.0`
Details: https://github.com/graphql/graphql-js/commit/183ff32bee4bc23eb23657f79f414c2400ecb06a#r32971387

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@abernix Merged as a bug fix 🎉 
Big thanks for the investigation 🕵

**Comment by IvanGoncharov** [comment]
@albertstill Can't release `14.3.1` with this fix until GitHub will fix webhooks:
https://twitter.com/githubstatus/status/1131255005909049345
I will keep you updated.

**Comment by IvanGoncharov** [comment]
@abernix `14.3.1` 📦 is published on NPM 🎉

**Comment by abernix** [comment]
Thank you, @IvanGoncharov!

**Pull request merged**
