### PR TITLE
incrementalDelivery: use experimental options rather than experimental functions

### PR DESCRIPTION
**Pull request by yaacovCR**
Using TS conditional types, when `enableExperimental` is set to true, return type of `execute` will correspond to the new types; otherwise, `execute` will return the old types.

When the option is set to `true`, incremental results will be delivered; otherwise, the `@defer` and `@stream` directives will be ignored.

@glasser @IvanGoncharov @robrichard @n1ru4l https://github.com/orgs/graphql/teams/graphql-js-reviewers

Not so experienced with conditional types, but from the test files, it seems to be working as expected, with the new return type selected only when setting the experimental option enableIncremental to true.

### CODE REVIEW

**Comment by yaacovCR** [comment]
@glasser @IvanGoncharov @robrichard @n1ru4l @graphql/graphql-js-reviewers 

Not so experienced with conditional types, but from the test files, it seems to be working as expected, with the new return type selected only when setting the experimental option `enableIncremental` to true.

**Comment by yaacovCR** [comment]
Now depends on #3727 which is the real  alternative to #3722

**Comment by yaacovCR** [comment]
The main motivation here is to create a flexible foundation if for some reason we need to support multiple experimental flags.

**Comment by glasser** [comment]
I don't have any strong opinions either way. I think that this change would mean that one could compile against graphql@17 but produce JS that works with graphql@16 without having to do any runtime probing for whether the new function exists, perhaps?  Or I guess you'd need to probe graphql version and use that to determine which value to pass.

**Comment by yaacovCR** [comment]
Yes, you'd need to figure out what value to pass.

**Comment by yaacovCR** [comment]
Of course, with existing solution you need to figure out which functions to call. The main advantage of the option approach is that if we introduce additional experimental options the number of functions does not become multiplicative.

**Comment by yaacovCR** [comment]
Closing in favor of #3722.

**Pull request closed without merging**
