### PR TITLE
fix(stream): continue on iterator error values

### PR DESCRIPTION
**Pull request by yaacovCR**
if the iterator errors when attempting to get the next value, we can assume subsequent calls to next will also error, and abort, but if we successfully get the next value, but it ends up triggering an error, we can continue, optimistic that the next value will not do so.

### CODE REVIEW

**Comment by yaacovCR** [comment]
@robrichard @IvanGoncharov this is more of a question than a PR -- what is the desired behavior?

**Comment by robrichard** [comment]
I don't think it's expected to receive more values after an async iterable throws an error. How is this handled with subscriptions?

**Comment by yaacovCR** [comment]
That’s just it, this code is not about the iterator returning an error, that’s further down. This code section is an error encountered in completion of a list item. With iterables, the next item is allowed to be processed, shouldn’t it be the same with async iterables?

**Comment by yaacovCR** [comment]
Added tests to explain

**Comment by robrichard** [comment]
@yaacovCR should this target the `asynciteratable` branch (https://github.com/graphql/graphql-js/pull/2757)? It doesn't seem to be bug in defer/stream, but rather the related feature of allowing async iterable return values from resolvers.

**Comment by yaacovCR** [comment]
Yes! Will rework when I have a moment to target that branch

**Comment by yaacovCR** [comment]
@robrichard @IvanGoncharov 

ready for review

**Comment by yaacovCR** [comment]
Bump, would this be accepted if rebased?

**Comment by robrichard** [comment]
@yaacovCR I pulled this in while rebasing. Thanks!

**Pull request closed without merging**
