### PR TITLE
Add test case for failing parsing

### PR DESCRIPTION
**Pull request by freiksenet**
Extend without fields followed by extend makes second extend to be parsed as types to implement. Note that locations are faulty in test (cause it's hard to deduce them).

### CODE REVIEW

**Comment by leebyron** [comment]
Great catch! Thanks for reporting this.

We may need to rethink field-less type extensions to solve for this ambiguity :/

**Comment by freiksenet** [comment]
I think allowing empty fields' blocks at parse time could work.

**Comment by leebyron** [comment]
Yeah, I think you're right. Requiring a fields block, but allowing the fields block to be empty might have to be the answer here, even though it's a bit inconsistent with other grammar rules in GraphQL :/

I'll do a bit of brainstorming with a few other folks and we'll resolve this quickly

**Comment by leebyron** [comment]
After brainstorming came up with what I think is a more consistent solution, though it does constitute more of a breaking change from existing usage. See #1169 for a path forward along with suggested migration tools

**Pull request merged**
