### PR TITLE
Fix error message typo for extend types

### PR DESCRIPTION
**Pull request by kommander**
Just a typo fix.

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@kommander Thanks a lot 👍 
Merged 🎉

**Comment by kommander** [comment]
🍪 🥛 btw. do you have an ETA for 14.2.0?

**Comment by IvanGoncharov** [comment]
@kommander I still need to implement a few major features that I promised for `14.2.0` so can't give exact ETA but I expect to finish it some time next week.
Note: you can use `master`: https://github.com/graphql/graphql-js#want-to-ride-the-bleeding-edge

**Comment by kommander** [comment]
I am using master, but didn't realise the npm branch had a prebuild master, thanks 👍

**Pull request merged**
