### PR TITLE
re-export collectFields

### PR DESCRIPTION
**Pull request by PabloSzx**

### CODE REVIEW

**Comment by ardatan** [comment]
Actually it would be nice to export `collectFields` directly from index file for the future.

**Comment by saihaj** [comment]
> Actually it would be nice to export `collectFields` directly from index file for the future.

That would be better. One more breaking change but I think we should do this now

**Comment by ardatan** [comment]
@saihaj If we both export `collectFields` from `execute` and index file, that won't be a breaking change, no?

**Comment by saihaj** [comment]
Yep 👍🏼

**Comment by PabloSzx** [comment]
> Yep 👍🏼

done :+1:

**Comment by IvanGoncharov** [comment]
@PabloSzx Thanks for PR `collectFields` was internal function.
So v15 and v16 have different prototypes (last 2 arguments have different types) so they are incompatible anyway even if we export them.
I'm totally ok with making this function part of public API but before that, I need to do some changes to it.

**Comment by PabloSzx** [comment]
@ardatan who is the lead maintainer of graphql-tools should be more interested in that comment

**Comment by robrichard** [comment]
Calling out here that the experimental defer/stream branch also changes the api of `collectFields`. 

https://github.com/graphql/graphql-js/pull/2839/files#diff-b17f02a116457aa7749e04b3f306eba462f95979d4f76c313a6073fa201e4fe4R52

I think we need to carefully consider the api of this function before making it external, so that we can support defer/stream without introducing additional breaking changes.

**Pull request closed without merging**
