### PR TITLE
Add Schema.injectType method #170

### PR DESCRIPTION
**Pull request by Sandreu**
Hello here is an implementation of injectType.

I didn't add tests since the constructor test code is already testing it :)

Regards.

### CODE REVIEW

**Comment by leebyron** [comment]
Can you clarify the purpose of this PR? I'm not sure I understand it from the code alone.

**Comment by Sandreu** [comment]
The situation is this one :

```
Interface Foo {
  a,
  b
}

Bar interfaces Foo {
  a,
  b,
  c
}

query {
  allFoos {...}
}
```

and the query
```
query {
  allFoos {
    a,
    b,
   ... on Bar {c}
  }
}
```

Then will not be able to solve `Bar` since the schema doesn't know it.

It works if you put a `resolveType` in `Foo` but if you want to deal with `isTypeOf`, it's not.
And even if you use `resolveType`, your introspection will not be aware of `Bar`

In fact, it may be a way to hide a branch of your tree from introspection ! ;)

So with this PR, you can do a `schema.injectType(barType)` if you don't want to hide it or use `isTypeOf` :)

I put an issue #170 about this.

Another way to solve this should be to add an option to the constructor to declare an array of orphan types... Perhaps it's even a better way... 

```
type GraphQLSchemaConfig = {
  query: GraphQLObjectType;
  mutation?: ?GraphQLObjectType;
  types?: ?Array;
}
```

**Comment by Sandreu** [comment]
I see it's not clear to put #170 in title :)

**Comment by dittos** [comment]
Why not just use `interfaces` field when creating GraphQLObjectType?

```
import {graphql, GraphQLInterfaceType, GraphQLObjectType, GraphQLString, GraphQLList, GraphQLSchema} from 'graphql';

var foo = new GraphQLInterfaceType({
  name: 'Foo',
  fields: {
    a: { type: GraphQLString },
    b: { type: GraphQLString },
  }
});

var bar = new GraphQLObjectType({
  name: 'Bar',
  fields: {
    a: { type: GraphQLString },
    b: { type: GraphQLString },
    c: { type: GraphQLString },
  },
  interfaces: [foo], // <=== this
  isTypeOf: () => true
});

var query = new GraphQLObjectType({
  name: 'Query',
  fields: {
    allFoos: { type: new GraphQLList(foo) }
  }
});

var schema = new GraphQLSchema({
  query: query
});

graphql(schema, `
{
  allFoos {
    __typename
    a,
    b,
    ... on Bar { c }
  }
}
`, {allFoos: [{a: 'a', b: 'b', c: 'c'}]}).then(result => {
    console.log(result.data.allFoos);
    // prints [ { __typename: 'Bar', a: 'a', b: 'b', c: 'c' } ]
});
```

**Comment by Sandreu** [comment]
You're definitively right... I don't know what I screwed up! I did have the interfaces field set but I think my GraphiQL windows hadn't an updated schema and I had a wrong red underline (because my request answer was all right).

Ok so, sorry for making you waste your time !

**Pull request closed without merging**
