### PR TITLE
feat: allow symbols as GraphQLSchema extension fields

### PR DESCRIPTION
**Pull request by n1ru4l**

### CODE REVIEW

**Review by IvanGoncharov — CHANGES_REQUESTED** [review]
@n1ru4l Symbols as extensions keys totally make sense.
Please add some basic tests.

As for `ObjMap` I'm don't understand motivation for this change.
Can you please clarify it?

**Comment by IvanGoncharov** [comment]
> @IvanGoncharov supporting TypeScript 4.3 prevents supporting symbols as index keys

Thanks for clarification 👍

**Comment by yaacovCR** [comment]
Flagging for v17

**Review by JoviDeCroock — APPROVED** [review]

**Comment by JoviDeCroock** [comment]
Part of v17 now

**Pull request closed without merging**
