### PR TITLE
[workflow] Fixing double run when creating a PR

### PR DESCRIPTION
**Pull request by gagoar**
Currently, the workflow runs twice every PR. This is caused by `push` and on `pull_request` events.
Sadly [the documentation says that it will be an or](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#example-using-a-list-of-events). 

But in practice, this triggers twice. 

Alternatively, we could just leave push
```yaml
on:  push
```

this is visible when inspecting some of the PR's 

image

every step produces 2 runs (one for push the other for pull_request) 
[example for pull request](https://github.com/graphql/graphql-js/pull/2861/checks?check_run_id=1454997986) 
[example for push](https://github.com/graphql/graphql-js/pull/2861/checks?check_run_id=1454997986)

this is also visible in #2757 
image

### CODE REVIEW

**Comment by gagoar** [comment]
I have a check failing that I can't reproduce. also I'm not changing code. 

```➜  graphql-js git:(gg/fixing-double-workflow-trigger) npm run prettier:check

> graphql@15.4.0 prettier:check /base/graphql-js
> prettier --check .

Checking formatting...
All matched files use Prettier code style!
```

**Comment by IvanGoncharov** [comment]
> I have a check failing that I can't reproduce. also I'm not changing code.

@gagoar In logs you will see:
image

**Comment by gagoar** [comment]
> > I have a check failing that I can't reproduce. also I'm not changing code.
> 
> @gagoar In logs you will see:
> image

I've run this on my computer but I can't seem to see what's the wrong part with what I've changed. can you tell me what is wrong?

**Comment by yaacovCR** [comment]
This can probably be closed considering all the improvements by @IvanGoncharov  within our use of GitHub actions. Feel free to reopen as necessary.

**Pull request closed without merging**
