### PR TITLE
Make "nonnull-test.js" more explicit

### PR DESCRIPTION
**Pull request by IvanGoncharov**
It was really hard to read those tests.
Moreover, explicit version is shorter and this PR increase line count only because I added `path` to every error.

### CODE REVIEW

**Comment by leebyron** [comment]
Looks like this has merge conflicts and test failures - want to take another look, @IvanGoncharov ?

**Comment by IvanGoncharov** [comment]
@leebyron Rebased and fixed. The reason was that #1286 changed the order of errors in a promise-heavy test. Not a problem since the order of error is implementation dependent. Maybe it worth to sort them, somehow?

It went unnoticed on master since `containSubset` doesn't check the order of elements in arrays.

**Comment by leebyron** [comment]
Aha, I'm glad we're migrating away from containSubset - the array order thing is not what I would have suspected

**Comment by leebyron** [comment]
Thanks for cleaning this up! It's much easier to follow now and I'm happy to see `path` included in the test expectations

**Pull request merged**
